.TH "pkcs11_make_hash_link" "1"
.SH "NAME"
.LP 
pkcs11_make_hash_link \- SmartCard PKCS#11 create a CA certificate link
.SH "SYNTAX"
.LP 
pkcs11_make_hash_link
.SH "DESCRIPTION"
.LP 
pkcs11_make_hash_link creates a symbolic hash-link for each CA certificate
and each CRL in the given directory
.SH "AUTHORS"
.LP 
Juan Antonio Martinez <jonsito@teleline.es>
.SH "SEE ALSO"
.LP 
pam_pkcs11(8)
.br 
PAM\-PKCS11 User Manual

