.TH "card_eventmgr" "1" "0.4.4" "Juan Antonio Martinez" "PAM-pkcs11 tools"
.SH "NAME"
card_eventmgr \- PCSC\-Lite Event Manager
.SH "SYNTAX"
.B card_eventmgr [\fI[no]debug\fP] [\fI[no]daemon\fP]
[\fItimeout=<\fImsecs\fP> ] [ config_file=<\fIfilename\fP> ]
.SH "DESCRIPTION"
card_eventmgr is a smart card monitoring tool that listen to the status of the
card reader and dispatch actions on several events. card_eventmgr can be
used for several actions: like screen lock on card removal.
.P
Three events are supported: card insertion, card removal and timeout on
removed card. Actions are specified in the configuration file.
.SH "OPTIONS"
.TP 
\fB[no]debug\fR 
Enable debugging output. Default is no debug.
.TP 
\fB[no]daemon\fR
Runs in background. If debug is unset, dettach also from tty. Default:
no daemon.
.TP 
\fBtimeout=<msecs>\fR
Set polling timeout in milliseconds. Defaults to 1000 (1 second).
.TP 
\fBconfig_file=<configuration file>\fR
Sets de configuration file. defaults to
\fI/etc/pam_pkcs11/card_eventmgr.conf\fP.
.SH "FILES"
\fI/etc/pam_pkcs11/card_eventmgr.conf\fP 
.SH "EXAMPLES"
To run this program the standard way type:
.P
card_eventmgr 
.P 
Alternativly you can specify options:
.P 
card_eventmgr nodebug nodaemon timeout=500 config_file=${HOME}/.card_eventmgr.conf
.SH "BUGS"
Some apps like [\fIxscreensaver\-command\fP] may fail due
to external events (eg: try to unlock an unlocked session).
In this case, the command incorrectly returns error code.
.P
User shoult take care on this circumstance.
.SH "AUTHORS"
Juan Antonio Martinez <jonsito@teleline.es>
.SH "SEE ALSO"
\fBpam_pkcs11\fP(8), \fBpkcs11_eventmgr\fP(1)
.br 
README.eventmgr
.br 
PAM\-PKCS11 User Manual
